"""
Telegram Signal Parser - Extracts all fields from trading signals
"""

import re
import json
from datetime import datetime
from typing import Dict, Optional
import logging

logger = logging.getLogger(__name__)

class TelegramSignalParser:
    """
    Parses Telegram messages into structured signal data.
    
    Example message:
    "GOLD: $2350.50 | Confidence: 85% week | STRONG SIGNAL | Source: LIVE
     Volatility: 0.00% | SL: 2340.00 | TP: 2370.00
     Support: 2345.00 | Resistance: 2360.00 | Timeframe: 15min"
    """
    
    # Asset name mapping
    ASSET_MAP = {
        'GOLD': 'XAU/USD',
        'SILVER': 'XAG/USD',
        'OIL': 'BCO/USD',
        'WTI': 'WTICO/USD',
        'SP500': 'S&P500/USD',
        'NASDAQ': 'NAS100/USD',
        'EURUSD': 'EURUSD',
        'GBPUSD': 'GBPUSD',
        'USDJPY': 'USDJPY',
        'BTC': 'BTC/USD',
        'ETH': 'ETH/USD'
    }
    
    def __init__(self):
        self.last_signal_id = 0
    
    def parse(self, message_text: str, message_id: int, chat_id: int) -> Optional[Dict]:
        """
        Extract all fields from Telegram message.
        Returns structured signal data.
        """
        
        signal_data = {
            'telegram_message_id': message_id,
            'telegram_chat_id': chat_id,
            'signal_timestamp': datetime.now(),
            'raw_message': message_text,
            'signal_uuid': None  # Will be generated by DB
        }
        
        # ========== 1. Extract Asset and Price ==========
        asset_patterns = [
            r'^([A-Za-z/]+):?\s*\$?([0-9,.]+)',  # GOLD: $2350.50
            r'^([A-Za-z/]+)\s+\$?([0-9,.]+)',     # GOLD $2350.50
            r'([A-Za-z/]+)\s+PRICE:\s*\$?([0-9,.]+)'  # GOLD PRICE: $2350.50
        ]
        
        for pattern in asset_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                asset_raw = match.group(1).upper().strip('/')
                # Map to standard symbol
                signal_data['asset_type'] = self.ASSET_MAP.get(asset_raw, asset_raw)
                price_str = match.group(2).replace(',', '')
                signal_data['current_price'] = float(price_str)
                break
        
        if 'asset_type' not in signal_data:
            logger.warning(f"Could not parse asset from: {message_text[:50]}")
            return None
        
        # ========== 2. Extract Confidence ==========
        conf_patterns = [
            r'Confidence:\s*([0-9.]+)%\s*(week)?',
            r'(\d+)%\s*confidence',
            r'confidence\s*(\d+)%',
            r'(\d+)%\s*(?:week|strong|signal)'
        ]
        
        for pattern in conf_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                signal_data['confidence_percent'] = float(match.group(1))
                break
        else:
            signal_data['confidence_percent'] = 75  # default
        
        # ========== 3. Extract Signal Strength ==========
        if 'STRONG' in message_text.upper():
            signal_data['signal_strength'] = 'STRONG_SIGNAL'
        elif 'WEAK' in message_text.upper():
            signal_data['signal_strength'] = 'WEAK'
        else:
            signal_data['signal_strength'] = 'SIGNAL'
        
        # ========== 4. Extract Data Source ==========
        source_patterns = [
            r'Source:\s*(\w+)',
            r'DATA:\s*(\w+)',
            r'FEED:\s*(\w+)'
        ]
        for pattern in source_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                signal_data['data_source'] = match.group(1).upper()
                break
        else:
            signal_data['data_source'] = 'LIVE'
        
        # ========== 5. Extract Volatility ==========
        vol_patterns = [
            r'Volatility:\s*([0-9.]+)%',
            r'VOL:\s*([0-9.]+)%',
            r'volatility\s*([0-9.]+)'
        ]
        for pattern in vol_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                signal_data['analysis_volatility'] = float(match.group(1))
                break
        else:
            signal_data['analysis_volatility'] = 0.5
        
        # ========== 6. Extract Stop Loss ==========
        sl_patterns = [
            r'SL:\s*\$?([0-9,.]+)',
            r'Stop\s+Loss:\s*\$?([0-9,.]+)',
            r'stop\s+(\d+(?:\.\d+)?)'
        ]
        for pattern in sl_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                sl_price = float(match.group(1).replace(',', ''))
                signal_data['stoploss'] = sl_price
                if 'current_price' in signal_data:
                    signal_data['stoploss_percent'] = round(
                        abs((sl_price - signal_data['current_price']) / signal_data['current_price'] * 100), 2
                    )
                break
        
        # ========== 7. Extract Take Profit ==========
        tp_patterns = [
            r'TP:\s*\$?([0-9,.]+)',
            r'Take\s+Profit:\s*\$?([0-9,.]+)',
            r'target\s+(\d+(?:\.\d+)?)'
        ]
        for pattern in tp_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                tp_price = float(match.group(1).replace(',', ''))
                signal_data['takeprofit'] = tp_price
                if 'current_price' in signal_data:
                    signal_data['takeprofit_percent'] = round(
                        abs((tp_price - signal_data['current_price']) / signal_data['current_price'] * 100), 2
                    )
                break
        
        # ========== 8. Extract Support Level ==========
        support_patterns = [
            r'Support:\s*\$?([0-9,.]+)',
            r'support\s+(\d+(?:\.\d+)?)',
            r'S1:\s*\$?([0-9,.]+)'
        ]
        for pattern in support_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                signal_data['support_level'] = float(match.group(1).replace(',', ''))
                break
        
        # ========== 9. Extract Resistance Level ==========
        resistance_patterns = [
            r'Resistance:\s*\$?([0-9,.]+)',
            r'resistance\s+(\d+(?:\.\d+)?)',
            r'R1:\s*\$?([0-9,.]+)'
        ]
        for pattern in resistance_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                signal_data['resistance_level'] = float(match.group(1).replace(',', ''))
                break
        
        # ========== 10. Extract Timeframe ==========
        tf_patterns = [
            r'(\d+)\s*(?:min|minute)',
            r'(\d+)\s*(?:hour|hr)',
            r'timeframe:\s*(\d+)',
            r'TF:\s*(\d+)'
        ]
        timeframe = 15  # default
        for pattern in tf_patterns:
            match = re.search(pattern, message_text, re.IGNORECASE)
            if match:
                value = int(match.group(1))
                if 'hour' in pattern or 'hr' in pattern:
                    timeframe = value * 60
                else:
                    timeframe = value
                break
        signal_data['timeframe_minutes'] = timeframe
        
        return signal_data
